apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ottoke-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Hritikraj8804/ottoke.git'
    targetRevision: feature/postgres-persistence
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ottoke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
