apiVersion: apps/v1
kind: Deployment
metadata:
  name: ottoke-backend
  namespace: ottoke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ottoke-backend
  template:
    metadata:
      labels:
        app: ottoke-backend
    spec:
      initContainers:
        - name: db-init
          image: hritikraj8804/ottoke-backend:latest
          command: ['python', 'scripts/seed_db.py']
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ottoke-db-secrets
                  key: DATABASE_URL
      containers:
        - name: backend
          image: hritikraj8804/ottoke-backend:latest
          env:
            - name: ALLOWED_ORIGINS
              value: "*"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ottoke-db-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              value: "redis://redis:6379/0"
          ports:
            - containerPort: 8000