apiVersion: v1
kind: Secret
metadata:
  name: ottoke-db-secrets
  namespace: ottoke
type: Opaque
stringData:
  POSTGRES_USER: "ottoke"
  POSTGRES_PASSWORD: "ottoke"
  POSTGRES_DB: "ottoke"
  DATABASE_URL: "postgresql://ottoke:ottoke@postgres:5432/ottoke"
