apiVersion: v1
kind: Service
metadata:
  name: {{ include "ottoke.fullname" . }}-postgres
  labels:
    {{- include "ottoke.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      name: postgres
  selector:
    app: {{ include "ottoke.fullname" . }}-postgres
