apiVersion: v1
kind: Service
metadata:
  name: {{ include "ottoke.fullname" . }}-redis
  labels:
    {{- include "ottoke.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      name: redis
  selector:
    app: {{ include "ottoke.fullname" . }}-redis
