apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ottoke.fullname" . }}-secrets
  labels:
    {{- include "ottoke.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.credentials.user }}:{{ .Values.postgres.credentials.password }}@{{ include "ottoke.fullname" . }}-postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.credentials.database }}"
  REDIS_URL: "redis://{{ include "ottoke.fullname" . }}-redis:{{ .Values.redis.service.port }}/0"
